# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

ruby '2.2.3'

gem 'rspec'
gem 'sinatra'
gem 'rspec-sinatra'
gem 'capybara'
gem 'rack-test'
gem 'rake'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'
gem 'pg'
