# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

ruby '2.3.0'
gem 'rspec'
gem 'sinatra'
gem 'rake'
gem 'database_cleaner'
gem 'capybara'
gem 'data_mapper'
gem 'dm-postgres-adapter'
# gem "rails"
